### ISSUE TITLE
Question: Separate Widgets

### ISSUE THREAD

**Issue by felipetesc** [oooutlk/tcltk#2]
This post is not about a  issue itself. Perhaps, it would be nice to open the section discussions ? 

Hello. I'm diving into the lib and I found slighly hard to separate the application into several functions. ~~No example has divided the ui into multiple methods~~, or across diferent files. So, the question arises: what's the  ~~"best (no such a thing)"~~ preferred way to create biggest projects and to separate each widget into a coese collection of elements ? 

How would you do it ? Any suggestions are welcome. Thanks.

**Comment by felipetesc** [comment]
> This post is not about a issue itself. Perhaps, it would be nice to open the section discussions ?
> 
> Hello. I'm diving into the lib and I found slighly hard to separate the application into several functions. ~No example has divided the ui into multiple methods~, or across diferent files. So, the question arises: what's the ~"best (no such a thing)"~ preferred way to create biggest projects and to separate each widget into a coese collection of elements ?
> 
> How would you do it ? Any suggestions are welcome. Thanks.

I found in the example canvas_a_simple_sketchpad_border_around_selected.rs the method:
```rust
fn set_color<Inst:TkInstance>( tk: &Tk<Inst>, canvas: &TkCanvas<Inst>, color: &Obj ) -> TkResult<()>
```
which can be used as a template, but we can also use the tree. I don't know which is the preferred alternative, though.

**Comment by oooutlk** [comment]
The [book directory](https://github.com/oooutlk/tcltk/tree/main/tk/book/) contains the [Tk tutorial](https://oooutlk.github.io/tk/) as the main document now. To build a local version, you can `cd tk/book; mdbook serve` then open the link `http://localhost:3000/`. The example `canvas_a_simple_sketchpad_border_around_selected.rs` is mentioned in its [tags chapter](https://oooutlk.github.io/tk/tags.html).

Unfortunately `cargo doc` failed in [docs.rs](https://docs.rs/crate/tk). I've know how to fix but not publish yet. Writing lots of doc comments for every API is boring and I don't have time spending on it( but I will update tk/README.md soon ).

Since this crate is literal translation of Tcl/Tk to some extend, I guess Tk programmers will find it easy to be familiar with the API of Rust equivalents.
